### ISSUE TITLE
Intersections of CpGrid do not implement indexInOutside

### ISSUE THREAD

**Issue by blattms** [OPM/dune-cornerpoint#115]

**Comment by atgeirr** [comment]
I would need some info about this issue to proceed: is it a new thing in Dune? In that case, from what version?

**Comment by blattms** [comment]
Nope, this is not a new thing. It has been in the interface for quite some time. I just realized that there is an implementation at https://github.com/OPM/dune-cornerpoint/blob/1d3e71b927efcb441dae7a69dc63983301108296/dune/grid/cpgrid/Intersection.hpp#L210. The question is whether it does the right thing. I am unable to judge this for myself.

**Comment by atgeirr** [comment]
I'll take a shot at reading the Dune docs, and see if I can understand what it *should* do, then figure out of it actually does it...

**Comment by atgeirr** [comment]
I have looked at the Dune docs, and I am pretty sure that the implementation is correct and follows the Dune interface (giving indices 0-5 corresponding to the Dune reference elements). It produces a result instead of throwing if there is no outside(), but that is ok I think by Dune: there it says that the result of calling outside() in that case is undefined, I guess that extends to indexInOutside(), too.

I guess this can be closed if you agree?

**Comment by blattms** [comment]
Agreed.
